# PureVox - Windows packaging script (PyInstaller + ZIP)
# Output: dist/PureVox-Windows-x64-<yyyy-MM-dd-HHmm>-release.zip
# Usage:  powershell -ExecutionPolicy Bypass -File build_win.ps1
$ErrorActionPreference = "Stop"

$date = Get-Date -Format 'yyyy-MM-dd-HHmm'
$zipFName = "PureVox-Windows-x64-$date-release"

# Prefer the bundled Python 3.8 (generated by bootstrap_python38.ps1 in packages\python38w)
# so the build is independent of the system Python. Fall back to python on PATH.
$embeddedPy = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "packages\python38w\python.exe"
if (Test-Path $embeddedPy) {
    $PY = $embeddedPy
} else {
    $PY = "python"
}

# 1. Build the C shared library (aimic.dll)
& $PY setup.py build_ext --inplace --force
if ($LASTEXITCODE -ne 0) { throw "build_ext failed" }

# 2. Generate version stamp (shown in the window title)
#    -NoNewline is PowerShell 6+/7 only; Win7 ships PS 5.1, so write without it
#    (a trailing newline in _build_version.py is harmless).
Set-Content _build_version.py "BUILD_DATE = `"$date`"" -Encoding UTF8

# 3. PyInstaller packaging
#    lazy-imported modules must be hidden-import (function-level `from xx import` is not
#    discovered statically)
& $PY -m PyInstaller --clean --name PureVox --noconsole --icon=audio_icon_on.ico `
    --hidden-import=pyaudio `
    --hidden-import=audio_processor `
    --hidden-import=dialog_about `
    --hidden-import=dialog_eq `
    --hidden-import=dialog_tse_reference `
    --hidden-import=spectrum_histogram `
    --hidden-import=wav_io `
    --hidden-import=vbcable_installer `
    --hidden-import=pvplatform.audio.pwpipe_client `
    --add-data="*.onnx;." `
    --add-data="audio_icon_on.ico;." `
    --add-data="audio_icon_off.ico;." `
    --add-data="aimic.dll;." `
    --add-data="html\*.html;html\" `
    --add-data="html\css\*.css;html\css\" `
    --add-data="html\js\*.js;html\js\" `
    --add-data="html\wasm\*;html\wasm\" `
    --add-data="server\*.py;server\" `
    --add-data="server\opus.dll;server\" `
    --add-data="packages\onnxruntime-win-x64-1.11.1\lib\onnxruntime.dll;." `
    --add-data="packages\onnxruntime-win-x64-1.11.1\lib\onnxruntime_providers_shared.dll;." `
    --exclude-module=pandas,scipy,matplotlib,unittest,tensorflow,torch,PIL `
    -y run_pyside6.py
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }

# 4. Remove unused files (~46MB: tcl/tk + unused PySide6 modules)
#    WARNING: Qt6Qml.dll / Qt6Quick.dll must NEVER be removed here. pyside6.abi3.dll
#    (the PySide6 core library every Qt*.pyd links) hard-imports Qt6Qml.dll; deleting
#    it makes `import QtWidgets` fail on Win7 with "DLL load failed ... specified module not found"
#    (verified 2026-08-09 via pefile + live Win7 EXE test). Qt6VirtualKeyboard.dll /
#    Qt6QmlModels.dll collected into the bundle also depend on Qml/Quick. Only Qt6Pdf.dll
#    and Qt6DataVisualization.dll are safe to drop (nothing in the import closure needs them).
Remove-Item dist\PureVox\_internal\tcl86t.dll, dist\PureVox\_internal\tk86t.dll, dist\PureVox\_internal\_tkinter.pyd -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\_tcl_data, dist\PureVox\_internal\_tk_data, dist\PureVox\_internal\tcl8 -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\opengl32sw.dll -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\Qt6Pdf.dll, dist\PureVox\_internal\PySide6\Qt6DataVisualization.dll -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\QtOpenGL.pyd, dist\PureVox\_internal\PySide6\QtQuick.pyd, dist\PureVox\_internal\PySide6\QtQml.pyd, dist\PureVox\_internal\PySide6\QtPdf.pyd -Force -ErrorAction SilentlyContinue

# 4b. Windows 7 compatibility: the bundled onnxruntime.dll imports the two
# Win10-only api-ms-win-* API-Set forwarders (verified with pefile: 6 symbols,
# all thin wrappers over kernel32) that do not exist on Win7 and are not present
# in the build runner's System32 either (API-Sets are resolved by the kernel on
# Win8+, they are not real files). Repo ships prebuilt x64 forwarding stubs in
# packages\onnxruntime-win-x64-1.11.1\lib that re-export these symbols via
# KERNEL32 (generated with mingw dlltool / compile from apiset/*.def). Copy both
# stubs next to onnxruntime.dll so Win7 can resolve them. Do not regress: Win10
# has no physical stub either, but its kernel resolves them virtually.
$repoApisets = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "packages\onnxruntime-win-x64-1.11.1\lib"
$win7ApiSets = @(
    "api-ms-win-core-libraryloader-l1-2-0.dll",
    "api-ms-win-core-processtopology-obsolete-l1-1-0.dll"
)
foreach ($api in $win7ApiSets) {
    $src = Join-Path $repoApisets $api
    if (-not (Test-Path "dist\PureVox\_internal\$api")) {
        if (Test-Path $src) {
            Copy-Item $src "dist\PureVox\_internal\$api" -Force
            Write-Host "Win7 api-set stub copied from repo: $api"
        } else {
            Write-Host "WARNING: api-set stub missing in repo: $api"
        }
    }
}
# MSVC runtime DLLs ship with the bundle so Win7 does not need a separate
# VC++ redistributable install for PureVox itself.
foreach ($vc in @("msvcp140.dll", "msvcp140_1.dll", "vcruntime140.dll", "vcruntime140_1.dll")) {
    $src = Join-Path $env:WINDIR ("System32\" + $vc)
    if (-not (Test-Path "dist\PureVox\_internal\$vc")) {
        if (Test-Path $src) {
            Copy-Item $src "dist\PureVox\_internal\$vc" -Force
            Write-Host "VC runtime copied: $vc"
        }
    }
}

# 5. Pack as a ZIP archive (no self-extracting EXE; timestamp rule reused from 7z)
Push-Location dist
..\packages\7z\7z.exe a "$zipFName.zip" "PureVox" | Out-Null
Pop-Location

# 6. Copy docs to the output directory (manual has a non-ASCII filename, match by glob)
Copy-Item *.html, CHANGELOG.md dist\ -Force

Write-Host "==> Done: dist/$zipFName.zip"