#!/bin/bash
# PureVox — Linux deb 打包脚本
# 产出: dist/PureVox-Linux-x64-<yyyy-MM-dd-HHmm>-release.deb
#
# 布局（与既有版本一致）:
#   /opt/purevox/          全部源码+.so+模型+html+pvplatform
#   /opt/purevox/python312  内嵌 Python 3.12（packages/python312 全量拷贝，
#                          PySide6 + zeroconf/aiohttp/cryptography/opuslib
#                          全部 pip 装好，与系统 Python 完全隔离）
#   /usr/bin/purevox       启动脚本 → 用内嵌 python312 跑 run_pyside6.py
#   /usr/share/applications/purevox.desktop
#   /usr/share/icons/hicolor/256x256/apps/purevox.png
#
# Depends: pipewire（音频走 pipewire-pulse 兼容层，pulsectl 经 ctypes 调系统 libpulse）；
#          numpy/onnxruntime/scipy 等 Python 依赖已捆绑进内嵌 python312。
# Python 依赖全部捆绑进 python312（与 AppImage 同一实现路径），不依赖系统
# python 及发行版 python 包名，故 Depends 只留 PipeWire，不再写任何 Python 依赖。
# 内嵌 python 由 GCC 15 编译（3.12.11），在新发行版（如 Debian 13）
# 需补 libcrypt.so.2 软链指向系统 libcrypt.so.1（libxcrypt ABI 兼容）才能加载。

set -euo pipefail
cd "$(dirname "$0")"

# 版本号解析：tag 触发 CI 时取自 GITHUB_REF_NAME（v2026.08.10.1517 → 2026.08.10.1517），
# 保证 deb/rpm/setup.py 与 tag 名完全一致、不因各 job 并发时刻漂移；本地/手动跑回退当前时间。
if [ -n "${GITHUB_REF_NAME:-}" ] && [[ "$GITHUB_REF_NAME" == v* ]]; then
    VERSION="${GITHUB_REF_NAME#v}"
else
    VERSION="$(date +%Y.%m.%d.%H%M)"
fi
REV="1"
# 文件名时间戳（yyyy-MM-dd-HHmm）：tag 触发时与 VERSION 同源，否则取当前时间
DATE="${VERSION//./-}"
PKG_FILE="PureVox-Linux-x64-${DATE}-release.deb"
ARCH="amd64"
DIST="dist"
STAGE="${TMPDIR:-/tmp}/purevox_deb_build"
ROOT="$STAGE/root"
CONTROL="$ROOT/DEBIAN/control"

echo "==> 准备打包目录 $STAGE"
rm -rf "$STAGE"
mkdir -p "$ROOT/opt/purevox" \
         "$ROOT/usr/bin" \
         "$ROOT/usr/share/applications" \
         "$ROOT/usr/share/icons/hicolor/256x256/apps" \
         "$ROOT/DEBIAN"

echo "==> 拷贝源码/图标"
for f in \
    audio_processor.py config_manager.py dialog_about.py dialog_eq.py logger.py \
    model_config.py run_pyside6.py spectrum_histogram.py theme_colors.py \
    dialog_tse_reference.py dialog_virtual_mic_linux.py ui_pyside6.py \
    user_paths.py wav_io.py \
    aimic.py; do
    cp "$f" "$ROOT/opt/purevox/"
done
mkdir -p "$ROOT/opt/purevox/models" "$ROOT/opt/purevox/assets/icons"
cp models/*.onnx "$ROOT/opt/purevox/models/"
cp assets/icons/*.ico "$ROOT/opt/purevox/assets/icons/"

echo "==> 捆绑内嵌 Python 3.12（packages/python312，含 PySide6 等全部 Python 依赖）"
# 与 pack_appimage.sh 一致：若内嵌 python 未编译则先引导（幂等）。CI 的
# ubuntu job 需先拉 packages/cpython 子模块（workflow 已处理）且装有 libssl-dev，
# 否则 bootstrap 编译出的解释器无 ssl、pip 无网络。
if [ ! -x "packages/python312/bin/python3" ]; then
    ./bootstrap_python312.sh
fi
cp -a packages/python312 "$ROOT/opt/purevox/python312"
# 内嵌 python 3.12.11 由 GCC 15 编译，链接 libcrypt.so.2；较新发行版
# （如 Debian 13）只有 libcrypt.so.1（libxcrypt，ABI 兼容），补软链使其可加载。
# 若构建机上本就存在 libcrypt.so.2 则跳过。
if [ ! -e "$ROOT/opt/purevox/python312/lib/libcrypt.so.2" ] && \
   [ -e /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0 ]; then
    ln -s /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0 \
        "$ROOT/opt/purevox/python312/lib/libcrypt.so.2"
fi

echo "==> 瘦身 PySide6（应用只用 QtWidgets/QtCore/QtGui，砍掉 qml/3D/Charts 等冗余，560M→~112M）"
bash tools/slim_pyside6.sh "$ROOT/opt/purevox/python312/lib/python3.12/site-packages/PySide6"

echo "==> 拷贝 html/"
cp -r html "$ROOT/opt/purevox/"

echo "==> 拷贝 server/（剔除 Windows opus.dll）"
mkdir -p "$ROOT/opt/purevox/server"
cp server/*.py "$ROOT/opt/purevox/server/"

echo "==> 拷贝 pvplatform/ 与 pvengine/"
cp -r pvplatform "$ROOT/opt/purevox/"
cp -r pvengine "$ROOT/opt/purevox/"
find "$ROOT/opt/purevox" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

echo "==> 生成版本戳 _build_version.py（窗口标题，与文件名/包版本同源）"
cat > "$ROOT/opt/purevox/_build_version.py" <<EOF
# Auto-generated by pack_deb.sh from tag/build time
BUILD_DATE = "$DATE"
EOF

echo "==> /usr/bin/purevox 启动脚本"
cat > "$ROOT/usr/bin/purevox" <<'EOF'
#!/bin/sh
# PureVox — AI 麦克风降噪
# 使用捆绑的内嵌 Python 3.12（/opt/purevox/python312，PySide6/numpy/onnxruntime
# 等全部依赖已随包携带），与系统 Python/发行版包名完全隔离。
export PYTHONHOME="/opt/purevox/python312"
export PATH="/opt/purevox/python312/bin:$PATH"
cd /opt/purevox || exit 1
exec /opt/purevox/python312/bin/python3.12 /opt/purevox/run_pyside6.py "$@"
EOF
chmod +x "$ROOT/usr/bin/purevox"

echo "==> desktop 文件"
cat > "$ROOT/usr/share/applications/purevox.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=PureVox
Name[zh_CN]=PureVox
GenericName=AI Mic Noise Reduction
GenericName[zh_CN]=AI 麦克风降噪
Comment=Real-time AI microphone noise reduction
Comment[zh_CN]=实时 AI 麦克风降噪
Exec=/usr/bin/purevox
Icon=purevox
Terminal=false
Categories=AudioVideo;Audio;Utility;
Keywords=mic;noise;denoise;audio;PureVox;
StartupNotify=false
EOF

echo "==> 图标 (ico → png)"
magick assets/icons/audio_icon_on.ico[0] -resize 256x256 \
    "$ROOT/usr/share/icons/hicolor/256x256/apps/purevox.png" 2>/dev/null \
 || python3 -c "
from PIL import Image
im = Image.open('assets/icons/audio_icon_on.ico')
im = im.convert('RGBA').resize((256, 256), Image.LANCZOS)
im.save('$ROOT/usr/share/icons/hicolor/256x256/apps/purevox.png')
"

echo "==> DEBIAN/control"
mkdir -p "$ROOT/DEBIAN"
cat > "$CONTROL" <<EOF
Package: purevox
Version: $VERSION-$REV
Section: sound
Priority: optional
Architecture: $ARCH
Maintainer: a2heng <752848283@qq.com>
Depends: pipewire, libopus0
Description: PureVox — Real-time AI microphone noise reduction
 Real-time AI audio denoising / target speech extraction / echo cancellation
 for the local microphone, with remote network streaming support.
 PureVox 实时 AI 麦克风降噪/目标提取/回声消除。
 .
 Python 运行时与全部 Python 依赖（PySide6 / zeroconf / aiohttp /
 cryptography / opuslib）已捆绑于包内 /opt/purevox/python312，与系统 Python
 完全隔离，不依赖发行版 python 包名，跨发行版可安装即用。
 .
 Linux 音频基于原生 PipeWire（libpipewire），格式协商 F32 单声道 48000Hz，
 重采样与声道转换由 PipeWire 负责。虚拟麦克风为单声道 null-sink
 purevox_out 的 monitor，其它应用可选 "PureVox 虚拟麦克风" 作为输入设备。
EOF

echo "==> 构建 $PKG_FILE"
mkdir -p "$DIST"
rm -f "$DIST/$PKG_FILE"
dpkg-deb --build --root-owner-group "$ROOT" "$DIST/$PKG_FILE" >/dev/null
echo "==> 完成: $DIST/$PKG_FILE"
dpkg-deb --info "$DIST/$PKG_FILE" | head -14 || true
