#!/bin/bash
# PureVox — Linux deb 打包脚本
# 产出: dist/PureVox-Linux-x64-<yyyy-MM-dd-HHmm>-release.deb
#
# 布局（与既有版本一致）:
#   /opt/purevox/          全部源码+.so+模型+html+pvplatform
#   /opt/purevox/python38  内嵌 Python 3.8（packages/python38 全量拷贝，
#                          PySide6 6.1.3 + zeroconf/aiohttp/cryptography/opuslib
#                          全部 pip 装好，与系统 Python 完全隔离）
#   /usr/bin/purevox       启动脚本 → 用内嵌 python38 跑 run_pyside6.py
#   /usr/share/applications/purevox.desktop
#   /usr/share/icons/hicolor/256x256/apps/purevox.png
#
# Depends: pipewire, libasound2（原生 C 运行库，名称跨发行版较一致）；
#          onnxruntime 捆绑预编译 1.11.1
# Python 依赖全部捆绑进 python38（与 AppImage 同一实现路径），不依赖系统
# python 及发行版 python 包名（AOSC: pyside6/zeroconf…，Debian:
# python3-pyside6… 命名各异且 Debian 无 PySide6 apt 包），故 Depends 只留
# 原生 C 运行库，不再写任何 Python 依赖。
# 内嵌 python 是 AOSC 用 GCC 15 编的（3.8.20），在新发行版（如 Debian 13）
# 需补 libcrypt.so.2 软链指向系统 libcrypt.so.1（libxcrypt ABI 兼容）才能加载。

set -euo pipefail
cd "$(dirname "$0")"

# 版本号解析：tag 触发 CI 时取自 GITHUB_REF_NAME（v2026.08.10.1517 → 2026.08.10.1517），
# 保证 deb/rpm/setup.py 与 tag 名完全一致、不因各 job 并发时刻漂移；本地/手动跑回退当前时间。
if [ -n "${GITHUB_REF_NAME:-}" ] && [[ "$GITHUB_REF_NAME" == v* ]]; then
    VERSION="${GITHUB_REF_NAME#v}"
else
    VERSION="$(date +%Y.%m.%d.%H%M)"
fi
REV="1"
# 文件名时间戳（yyyy-MM-dd-HHmm）：tag 触发时与 VERSION 同源，否则取当前时间
DATE="${VERSION//./-}"
PKG_FILE="PureVox-Linux-x64-${DATE}-release.deb"
ARCH="amd64"
DIST="dist"
STAGE="${TMPDIR:-/tmp}/purevox_deb_build"
ROOT="$STAGE/root"
CONTROL="$ROOT/DEBIAN/control"

echo "==> 构建纯 C 共享库 (libaimic.so + libpvpipe.so + libpvalsa.so)"
python3 setup.py build_ext --inplace --force >/dev/null
[ -f "libaimic.so" ] || { echo "缺少 libaimic.so"; exit 1; }
[ -f "libpvpipe.so" ] || { echo "缺少 libpvpipe.so"; exit 1; }
[ -f "libpvalsa.so" ] || { echo "缺少 libpvalsa.so"; exit 1; }

echo "==> 准备打包目录 $STAGE"
rm -rf "$STAGE"
mkdir -p "$ROOT/opt/purevox" \
         "$ROOT/usr/bin" \
         "$ROOT/usr/share/applications" \
         "$ROOT/usr/share/icons/hicolor/256x256/apps" \
         "$ROOT/DEBIAN"

echo "==> 拷贝源码/模型/图标"
for f in \
    audio_processor.py config_manager.py dialog_about.py dialog_eq.py logger.py \
    model_config.py run_pyside6.py spectrum_histogram.py theme_colors.py \
    dialog_tse_reference.py dialog_virtual_mic_linux.py ui_pyside6.py \
    user_paths.py wav_io.py \
    aimic.py pvpipe.py pvalsa.py \
    aec9_ep0544.onnx tse15_stream_ep_0673.onnx v9_fft2048_band256_epoch_261.onnx \
    audio_icon_off.ico audio_icon_on.ico; do
    cp "$f" "$ROOT/opt/purevox/"
done
cp "libaimic.so" "$ROOT/opt/purevox/"
cp "libpvpipe.so" "$ROOT/opt/purevox/"
cp "libpvalsa.so" "$ROOT/opt/purevox/"

echo "==> 拷贝捆绑的 onnxruntime 1.11.1 动态库（aimic 链接 libonnxruntime.so.1.11.1）"
cp packages/onnxruntime-linux-x64-1.11.1/lib/libonnxruntime.so* "$ROOT/opt/purevox/"

echo "==> 捆绑内嵌 Python 3.8（packages/python38，含 PySide6 等全部 Python 依赖）"
cp -a packages/python38 "$ROOT/opt/purevox/python38"
# 内嵌 python 3.8.20 由 AOSC GCC 15 编译，链接 libcrypt.so.2；较新发行版
# （如 Debian 13）只有 libcrypt.so.1（libxcrypt，ABI 兼容），补软链使其可加载。
# 若构建机上本就存在 libcrypt.so.2 则跳过。
if [ ! -e "$ROOT/opt/purevox/python38/lib/libcrypt.so.2" ] && \
   [ -e /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0 ]; then
    ln -s /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0 \
        "$ROOT/opt/purevox/python38/lib/libcrypt.so.2"
fi

echo "==> 瘦身 PySide6（应用只用 QtWidgets/QtCore/QtGui，砍掉 qml/3D/Charts 等冗余，560M→~112M）"
bash scripts/slim_pyside6.sh "$ROOT/opt/purevox/python38/lib/python3.8/site-packages/PySide6"

echo "==> 拷贝 html/"
cp -r html "$ROOT/opt/purevox/"

echo "==> 拷贝 server/（剔除 Windows opus.dll）"
mkdir -p "$ROOT/opt/purevox/server"
cp server/*.py "$ROOT/opt/purevox/server/"

echo "==> 拷贝 pvplatform/"
cp -r pvplatform "$ROOT/opt/purevox/"
find "$ROOT/opt/purevox" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

echo "==> 生成版本戳 _build_version.py（窗口标题，与文件名/包版本同源）"
cat > "$ROOT/opt/purevox/_build_version.py" <<EOF
# Auto-generated by pack_deb.sh from tag/build time
BUILD_DATE = "$DATE"
EOF

echo "==> /usr/bin/purevox 启动脚本"
cat > "$ROOT/usr/bin/purevox" <<'EOF'
#!/bin/sh
# PureVox — AI 麦克风降噪
# 使用捆绑的内嵌 Python 3.8（/opt/purevox/python38，PySide6 等全部依赖已随包携带），
# 与系统 Python/发行版包名完全隔离。aimic.so 链捆绑的预编译 onnxruntime 提前注入
# LD_LIBRARY_PATH；内嵌 python 的 lib 目录同理（含 libcrypt.so.2 软链）。
export LD_LIBRARY_PATH="/opt/purevox:/opt/purevox/python38/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONHOME="/opt/purevox/python38"
export PATH="/opt/purevox/python38/bin:$PATH"
cd /opt/purevox || exit 1
exec /opt/purevox/python38/bin/python3.8 /opt/purevox/run_pyside6.py "$@"
EOF
chmod +x "$ROOT/usr/bin/purevox"

echo "==> desktop 文件"
cat > "$ROOT/usr/share/applications/purevox.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=PureVox
Name[zh_CN]=PureVox
GenericName=AI Mic Noise Reduction
GenericName[zh_CN]=AI 麦克风降噪
Comment=Real-time AI microphone noise reduction
Comment[zh_CN]=实时 AI 麦克风降噪
Exec=/usr/bin/purevox
Icon=purevox
Terminal=false
Categories=AudioVideo;Audio;Utility;
Keywords=mic;noise;denoise;audio;PureVox;
StartupNotify=false
EOF

echo "==> 图标 (ico → png)"
magick audio_icon_on.ico[0] -resize 256x256 \
    "$ROOT/usr/share/icons/hicolor/256x256/apps/purevox.png" 2>/dev/null \
 || python3 -c "
from PIL import Image
im = Image.open('audio_icon_on.ico')
im = im.convert('RGBA').resize((256, 256), Image.LANCZOS)
im.save('$ROOT/usr/share/icons/hicolor/256x256/apps/purevox.png')
"

echo "==> DEBIAN/control"
mkdir -p "$ROOT/DEBIAN"
cat > "$CONTROL" <<EOF
Package: purevox
Version: $VERSION-$REV
Section: sound
Priority: optional
Architecture: $ARCH
Maintainer: a2heng <752848283@qq.com>
Depends: pipewire, libasound2
Description: PureVox — Real-time AI microphone noise reduction
 Real-time AI audio denoising / target speech extraction / echo cancellation
 for the local microphone, with remote network streaming support.
 PureVox 实时 AI 麦克风降噪/目标提取/回声消除。
 .
 Python 运行时与全部 Python 依赖（PySide6 6.1.3 / zeroconf / aiohttp /
 cryptography / opuslib）已捆绑于包内 /opt/purevox/python38，与系统 Python
 完全隔离，不依赖发行版 python 包名，跨发行版可安装即用。
 .
 Linux 音频基于原生 PipeWire（libpipewire），格式协商 F32 单声道 48000Hz，
 重采样与声道转换由 PipeWire 负责。虚拟麦克风为单声道 null-sink
 purevox_out 的 monitor，其它应用可选 "PureVox 虚拟麦克风" 作为输入设备。
EOF

echo "==> 构建 $PKG_FILE"
mkdir -p "$DIST"
rm -f "$DIST/$PKG_FILE"
dpkg-deb --build --root-owner-group "$ROOT" "$DIST/$PKG_FILE" >/dev/null
echo "==> 完成: $DIST/$PKG_FILE"
dpkg-deb --info "$DIST/$PKG_FILE" | head -14 || true
