# PureVox - Windows packaging script (PyInstaller bundle)
# Output: dist/PureVox/  (PyInstaller one-folder bundle; CI uploads this dir and
#                        GitHub artifacts compress it to a .zip automatically)
# Usage:  powershell -ExecutionPolicy Bypass -File build_win.ps1
$ErrorActionPreference = "Stop"

# Version stamp shown in the window title. On tag-triggered CI, take it from
# GITHUB_REF_NAME (v<yyyy.MM.dd.HHmm> -> yyyy-MM-dd-HHmm) so the title matches
# the tag / artifact filename instead of the runner's local build time; local
# builds fall back to the current time. (Pure ASCII: PS 5.1 / Win7 safe.)
$ref = $env:GITHUB_REF_NAME
if ($ref -and $ref.StartsWith("v") -and $ref.Length -gt 1) {
    $date = $ref.Substring(1).Replace(".", "-")
} else {
    $date = Get-Date -Format 'yyyy-MM-dd-HHmm'
}

# Prefer the bundled Python 3.12 (generated by bootstrap_python312.ps1 in packages\python312w)
# so the build is independent of the system Python. Fall back to python on PATH.
$embeddedPy = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "packages\python312w\python.exe"
if (Test-Path $embeddedPy) {
    $PY = $embeddedPy
} else {
    $PY = "python"
}

# 1. Build the C shared library (aimic.dll)
& $PY setup.py build_ext --inplace --force
if ($LASTEXITCODE -ne 0) { throw "build_ext failed" }

# 2. Generate version stamp (shown in the window title)
#    -NoNewline is PowerShell 6+/7 only; Win7 ships PS 5.1, so write without it
#    (a trailing newline in _build_version.py is harmless).
Set-Content _build_version.py "BUILD_DATE = `"$date`"" -Encoding UTF8

# 3. PyInstaller packaging
#    lazy-imported modules must be hidden-import (function-level `from xx import` is not
#    discovered statically)
& $PY -m PyInstaller --clean --name PureVox --noconsole --icon=audio_icon_on.ico `
    --hidden-import=pyaudio `
    --hidden-import=audio_processor `
    --hidden-import=dialog_about `
    --hidden-import=dialog_eq `
    --hidden-import=dialog_tse_reference `
    --hidden-import=spectrum_histogram `
    --hidden-import=wav_io `
    --hidden-import=dialog_vbcable_check `
    --hidden-import=pvplatform.audio.pwpipe_client `
    --add-data="*.onnx;." `
    --add-data="audio_icon_on.ico;." `
    --add-data="audio_icon_off.ico;." `
    --add-data="aimic.dll;." `
    --add-data="html\*.html;html\" `
    --add-data="html\css\*.css;html\css\" `
    --add-data="html\js\*.js;html\js\" `
    --add-data="html\wasm\*;html\wasm\" `
    --add-data="server\*.py;server\" `
    --add-data="server\opus.dll;server\" `
    --add-data="packages\onnxruntime-win-x64-1.22.0\lib\onnxruntime.dll;." `
    --add-data="packages\onnxruntime-win-x64-1.22.0\lib\onnxruntime_providers_shared.dll;." `
    --exclude-module=pandas,scipy,matplotlib,unittest,tensorflow,torch,PIL `
    -y run_pyside6.py
if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }

# 4. Remove unused files (~46MB: tcl/tk + unused PySide6 modules)
#    WARNING: Qt6Qml.dll / Qt6Quick.dll must NEVER be removed here. pyside6.abi3.dll
#    (the PySide6 core library every Qt*.pyd links) hard-imports Qt6Qml.dll; deleting
#    it makes `import QtWidgets` fail on Win7 with "DLL load failed ... specified module not found"
#    (verified 2026-08-09 via pefile + live Win7 EXE test). Qt6VirtualKeyboard.dll /
#    Qt6QmlModels.dll collected into the bundle also depend on Qml/Quick. Only Qt6Pdf.dll
#    and Qt6DataVisualization.dll are safe to drop (nothing in the import closure needs them).
Remove-Item dist\PureVox\_internal\tcl86t.dll, dist\PureVox\_internal\tk86t.dll, dist\PureVox\_internal\_tkinter.pyd -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\_tcl_data, dist\PureVox\_internal\_tk_data, dist\PureVox\_internal\tcl8 -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\opengl32sw.dll -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\Qt6Pdf.dll, dist\PureVox\_internal\PySide6\Qt6DataVisualization.dll -Force -ErrorAction SilentlyContinue
Remove-Item dist\PureVox\_internal\PySide6\QtOpenGL.pyd, dist\PureVox\_internal\PySide6\QtQuick.pyd, dist\PureVox\_internal\PySide6\QtQml.pyd, dist\PureVox\_internal\PySide6\QtPdf.pyd -Force -ErrorAction SilentlyContinue

# MSVC runtime DLLs ship with the bundle so no separate VC++ redistributable needed.
foreach ($vc in @("msvcp140.dll", "msvcp140_1.dll", "vcruntime140.dll", "vcruntime140_1.dll")) {
    $src = Join-Path $env:WINDIR ("System32\" + $vc)
    if (-not (Test-Path "dist\PureVox\_internal\$vc")) {
        if (Test-Path $src) {
            Copy-Item $src "dist\PureVox\_internal\$vc" -Force
            Write-Host "VC runtime copied: $vc"
        }
    }
}

# (no doc copy step: the 关于 dialog embeds the manuals and the changelog
#  entirely in dialog_about.py; CHANGELOG.md / 用户手册.html are deleted)

Write-Host "==> Done: dist/PureVox"
