#ifndef LIBSAMPLERATE_CONFIG_H
#define LIBSAMPLERATE_CONFIG_H

#define PACKAGE "libsamplerate"
#define VERSION "0.2.1"

#define HAVE_STDINT_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_IMMINTRIN_H 1

#define ENABLE_SINC_FAST_CONVERTER 1
#define ENABLE_SINC_MEDIUM_CONVERTER 1
#define ENABLE_SINC_BEST_CONVERTER 1

#endif
